### ISSUE TITLE
Pause-Continue bug (P + G spam)

### ISSUE THREAD

**Issue by IvanRistovic** [MATF-RG16/RG16-012-game-of-life#1]
Posle iscrtavanja svakog sloja, height se povecava. Sloj se crta (tj PostRedisplay se poziva u timeru) ako animationRunning nije 0. Ako se  spamuje P i G par sekundi, za kratko vreme ce taj indikator biti 1, i nasilno ce se pozivati onDisplay i menjati height, sto ja verujem da uzrokuje ovaj lep bagic:

![ss](http://i.imgur.com/Nue6xdL.gif)

**EDIT**: Coincidence?
![ss](http://i.imgur.com/Vd6RAuV.png)

**Comment by milana-kovacevic** [comment]
Da da, znam za taj bag sa  pauziranjem, ali nisam se jos bavila njim. Mada, nije mi ni palo na pamet da spamujem P i G :smiley: 
Cim ispravim ovaj malecni  bag koji sam ranije primetila trebalo bi i ovaj da bude resen. 
Hvala na primedbi! U sledecem commitu sredjujem ovo.

**Comment by milana-kovacevic** [comment]
Obavestavam te da ovaj bag vise ne postoji :fire: :bug: :fire: 
Uzivaj u mojoj animaciji i jos jednom hvala na pomoci da usavrsim svoj projakat! :wink:
