### ISSUE TITLE
Snimak ekrana

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-012-game-of-life#2]
Napravite snimak ekrana od 30-ak sekundi za demonstraciju igre. Neka bude 800x600 rezolucija, format zapisa mpg.

**Comment by milana-kovacevic** [comment]
Snimak mozete preuzeti [ovde](https://1drv.ms/f/s!ArZM24AUjE14mGKAklrQt3u-QAY_).  :movie_camera:
